server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            - id: event-service
              uri: lb://event-service
              predicates:
                - Path=/events/**