server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:file:./data/eventdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true